# Generated by Django 4.0.2 on 2022-02-10 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameweeks", "0001_initial"),
        ("matches", "0002_alter_match_options_alter_match_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="gameweek",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="gameweeks.gameweek",
            ),
        ),
    ]
