# Generated by Django 4.0.2 on 2022-02-14 12:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_understat_id'),
        ('scripts', '0002_generateunderlyingstatdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerateUnderstatPlayerIdData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('understat_team_id', models.CharField(max_length=32)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
            options={
                'verbose_name_plural': 'Generate understat player id data',
            },
        ),
    ]
