# Generated by Django 4.0.2 on 2022-02-11 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
        ("scripts", "0003_generateplayerspointdata_end_fpl_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generateplayerspointdata",
            name="end_fpl_id",
        ),
        migrations.RemoveField(
            model_name="generateplayerspointdata",
            name="start_fpl_id",
        ),
        migrations.AddField(
            model_name="generateplayerspointdata",
            name="teams",
            field=models.ForeignKey(
                default="637b81da-de9b-49d8-a245-9131aa2b2ebb",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generate_players_point_data",
                to="teams.team",
            ),
            preserve_default=False,
        ),
    ]
