# Generated by Django 4.0.2 on 2022-02-11 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0004_remove_generateplayerspointdata_end_fpl_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generateplayerspointdata',
            old_name='teams',
            new_name='team',
        ),
    ]
