# Generated by Django 4.0.2 on 2022-02-11 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameweeks', '0001_initial'),
        ('scripts', '0006_generateplayerspointdata_gameweek_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generateplayerspointdata',
            name='gameweek',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generate_players_point_data', to='gameweeks.gameweek'),
        ),
    ]
