# Generated by Django 4.0.2 on 2022-02-10 01:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
        ('matches', '0001_initial'),
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShotsData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_goal', models.FloatField()),
                ('result', models.CharField(choices=[('Goal', 'Goal'), ('SavedShot', 'Saved'), ('BlockedShot', 'Blocked'), ('MissedShots', 'Missed')], max_length=32)),
                ('minute', models.CharField(max_length=32)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots_data', to='matches.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots_data', to='players.player')),
                ('player_assisted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assist_shots_data', to='players.player')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
