# Generated by Django 4.0.2 on 2022-02-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='underlyingstat',
            name='minutes',
            field=models.IntegerField(default=0),
        ),
    ]
