# Generated by Django 4.0.2 on 2022-02-10 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_shotsdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shotsdata',
            options={'verbose_name_plural': 'Shots data'},
        ),
    ]
