# Generated by Django 4.0.2 on 2022-02-12 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0002_underlyingstat_minutes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="underlyingstat",
            old_name="npxG",
            new_name="xG",
        ),
    ]
