# Generated by Django 4.0.2 on 2022-02-09 02:44

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0001_initial"),
        ("players", "0001_initial"),
        ("stats", "0003_previousseasontotalpoint"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerBettingOdd",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identifier",
                    models.CharField(
                        choices=[
                            ("goals_scored", "goals_scored"),
                            ("assists", "assists"),
                        ],
                        max_length=32,
                    ),
                ),
                ("number", models.IntegerField(default=0)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_betting_odds",
                        to="matches.match",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_betting_odds",
                        to="players.player",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
