# Generated by Django 4.0.2 on 2022-02-14 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0002_player_understat_id"),
        ("stats", "0003_rename_npxg_underlyingstat_xg"),
    ]

    operations = [
        migrations.AddField(
            model_name="underlyingstat",
            name="player",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="players.player",
            ),
            preserve_default=False,
        ),
    ]
