# Generated by Django 4.0.2 on 2022-02-10 05:29

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fpl_id", models.IntegerField(unique=True)),
                ("first_name", models.CharField(max_length=128)),
                ("last_name", models.CharField(max_length=128)),
                ("display_name", models.CharField(max_length=128)),
                ("price", models.IntegerField()),
                ("photo_id", models.CharField(max_length=32)),
                (
                    "chance_of_playing_this_round",
                    models.IntegerField(
                        blank=True,
                        choices=[(100, 0), (75, 75), (50, 50), (25, 25)],
                        default=100,
                        null=True,
                    ),
                ),
                (
                    "chance_of_playing_next_round",
                    models.IntegerField(
                        blank=True,
                        choices=[(100, 0), (75, 75), (50, 50), (25, 25)],
                        default=100,
                        null=True,
                    ),
                ),
                (
                    "position",
                    models.IntegerField(
                        choices=[
                            (1, "Goalkeeper"),
                            (2, "Defender"),
                            (3, "Midfielder"),
                            (4, "Forward"),
                        ]
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
