# Generated by Django 4.0.2 on 2022-02-10 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="position",
            field=models.CharField(
                choices=[
                    ("goalkeeper", "Goalkeeper"),
                    ("defender", "Defender"),
                    ("midfielder", "Midfielder"),
                    ("forward", "Forward"),
                ],
                default="goalkeeper",
                max_length=16,
            ),
            preserve_default=False,
        ),
    ]
